version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    env_file:
      - path: .env
        required: true
    environment:          
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:     
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/etc/data
    ports:
      - "${POSTGRES_PORT}:5432"

  hyperdrive.service:
    container_name: service
    image: ${DOCKER_REGISTRY-}hyperdriveservice
    build:
      context: .
      dockerfile: Hyperdrive.Service/Dockerfile
    environment:            
       ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
       ASPNETCORE_URLS:  ${ASPNETCORE_URLS}
       PUBLIC_URL: ${PUBLIC_URL}
       OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
       APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
       ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
       Jwt__JwtAudiences: ${JWT_AUDIENCES}
       Jwt__JwtExpireMinutes: ${JWT_EXPIRE_MINUTES}
       Jwt__JwtExpireDays: ${JWT_EXPIRE_DAYS}
       Jwt__JwtAuthority: ${JWT_AUTHORITY}
       Jwt__JwtIssuer: ${JWT_ISSUER}
       Jwt__JwtKey: ${JWT_KEY}
       RateLimit__PolicyName: ${RATELIMIT_POLICYNAME}
       RateLimit__PermitLimit: ${RATELIMIT_PERMITLIMIT}
       RateLimit__QueueProcessingOrder: ${RATELIMIT_QUEUEPROCESSINGORDER}
       RateLimit__QueueLimit: ${RATELIMIT_QUEUELIMIT}      
    ports:
      - "5000:80"
      - "5001:443"

    depends_on:
      - db

volumes:
  db-data: