networks:
  monitoring:
    driver: bridge

services:
  db: #DATABASE
    container_name: db
    image: postgres
    restart: always
    user: postgres
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/etc/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - monitoring


  service: #API
    container_name: service
    image: ${DOCKER_REGISTRY-}hyperdriveservice
    build:
      context: .
      dockerfile: Hyperdrive.Service/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
      ASPNETCORE_HTTPS_PORTS: ${ASPNETCORE_HTTPS_PORTS}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
      Jwt__JwtAudiences: ${JWT_AUDIENCES}
      Jwt__JwtExpireMinutes: ${JWT_EXPIRE_MINUTES}
      Jwt__JwtExpireDays: ${JWT_EXPIRE_DAYS}
      Jwt__JwtAuthority: ${JWT_AUTHORITY}
      Jwt__JwtIssuer: ${JWT_ISSUER}
      Jwt__JwtKey: ${JWT_KEY}
      RateLimit__PolicyName: ${RATELIMIT_POLICYNAME}
      RateLimit__PermitLimit: ${RATELIMIT_PERMITLIMIT}
      RateLimit__QueueProcessingOrder: ${RATELIMIT_QUEUEPROCESSINGORDER}
      RateLimit__QueueLimit: ${RATELIMIT_QUEUELIMIT}
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"
      - "${ASPNETCORE_HTTPS_PORTS}:${ASPNETCORE_HTTPS_PORTS}"
    networks:
      - monitoring
    depends_on:
      - db


  tempo: # TRACES BACKEND
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "--config.file=/etc/tempo/tempo.yaml" ] # Force config
    ports:
      - "${TEMPO_GRPC_PORT}:${TEMPO_GRPC_PORT}"
      - "${TEMPO_HTTP_PORT}:${TEMPO_HTTP_PORT}"
    volumes:    
      - tempo-data:/var/tempo
      - ./otel/tempo.yaml:/etc/tempo/tempo.yaml
    networks:
      - monitoring 


  prometheus: #METRICS BACKEND
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    volumes:
      - ./otel/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-otlp-receiver
    networks:
      - monitoring
    restart: unless-stopped


  loki: #LOGS BACKEND
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"
    networks:
      - monitoring


  alloy: #OTEL COLLECTOR
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./otel/alloy.yaml:/etc/alloy/config.yaml
      - alloy-data:/alloy
    ports:
      - "${ALLOY_UI_PORT}:${ALLOY_UI_PORT}"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki
      - tempo      

volumes:
  db-data:
  prom-data:
  alloy-data:
  tempo-data:
