networks:
  monitoring:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/etc/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - monitoring


  service:
    container_name: service
    image: ${DOCKER_REGISTRY-}hyperdriveservice
    build:
      context: .
      dockerfile: Hyperdrive.Service/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
      ASPNETCORE_HTTPS_PORTS: ${ASPNETCORE_HTTPS_PORTS}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
      Jwt__JwtAudience: ${JWT_AUDIENCE}    
      Jwt__JwtAuthority: ${JWT_AUTHORITY}
      Jwt__JwtIssuer: ${JWT_ISSUER}
      Jwt__JwtKey: ${JWT_KEY}
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"
      - "${ASPNETCORE_HTTPS_PORTS}:${ASPNETCORE_HTTPS_PORTS}"
    networks:
      - monitoring
    depends_on:
      - db

volumes:
  db-data:
