name: Main - Build .NET Service

on:
  push:
    branches: [ main ]    
    paths:
        - 'Hyperdrive.Main.Service/**'

  pull_request:
    branches: [ main ]
    paths:
        - 'Hyperdrive.Main.Service/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: Hyperdrive.Main.Service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v5

      - name: ğŸ› ï¸ Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: ğŸ“¥ Restore dependencies
        run: dotnet restore --locked-mode Hyperdrive.Main.Service/Hyperdrive.Main.Service.csproj

      - name: â™»ï¸ Clean project
        run: dotnet clean Hyperdrive.Main.Service/Hyperdrive.Main.Service.csproj

      - name: ğŸ—ï¸ Build project
        run: dotnet build --no-restore Hyperdrive.Main.Service/Hyperdrive.Main.Service.csproj    
