name: Build .NET Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

defaults:
  run:
    working-directory: Hyperdrive.Service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v5

      - name: ğŸ› ï¸ Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: ğŸ“¥ Restore dependencies
        run: dotnet restore Hyperdrive.Service/Hyperdrive.Service.csproj

      - name: â™»ï¸ Clean project
        run: dotnet clean Hyperdrive.Service/Hyperdrive.Service.csproj

      - name: ğŸ—ï¸ Build project
        run: dotnet build --no-restore Hyperdrive.Service/Hyperdrive.Service.csproj

      - name: ğŸ‹ Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: â¹ Stop containers
        run: docker compose down --remove-orphans

      - name: ğŸ—ï¸ Build containers
        run: docker compose build
