name: Test .NET Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read  

defaults:
  run:
    working-directory: Hyperdrive.Main.Service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v5

      - name: ğŸ› ï¸ Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'      

      - name: ğŸ“¥ Restore dependencies
        run: dotnet restore --locked-mode Hyperdrive.Main.Test.Infrastructure/Hyperdrive.Main.Test.Infrastructure.csproj     

      - name: â™»ï¸ Clean project
        run: dotnet clean Hyperdrive.Main.Test.Infrastructure/Hyperdrive.Main.Test.Infrastructure.csproj          
       
      - name: ğŸ—ï¸ Build project
        run: dotnet build --no-restore Hyperdrive.Main.Test.Infrastructure/Hyperdrive.Main.Test.Infrastructure.csproj    

      - name: âœ… Run tests
        run: dotnet test Hyperdrive.Main.Test.Infrastructure/Hyperdrive.Main.Test.Infrastructure.csproj --no-build

