name: Build & Test .NET API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read  

defaults:
  run:
    working-directory: Hyperdrive.Service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: ğŸ“¥ Restore dependencies
        run:  | 
          dotnet restore Hyperdrive.Service.csproj
          dotnet restore Hyperdrive.Test.Infrastructure.csproj

      - name: â™»ï¸ Clean project
        run: | 
          dotnet clean Hyperdrive.Service.csproj
          dotnet clean Hyperdrive.Test.Infrastructure.csproj

      - name: ğŸ—ï¸ Build project
        run: |
          dotnet build --no-restore Hyperdrive.Service.csproj
          dotnet build --no-restore Hyperdrive.Test.Infrastructure.csproj

      - name: âœ… Run tests
        run: dotnet test Hyperdrive.Test.Infrastructure --no-build

